# Exported from Render on 2025-07-25T15:31:20Z
databases:
- name: database
  databaseName: database_hz3j_00np
  user: database_hz3j_user
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"




services:
- type: web
  name: PROYECTO-LAB
  runtime: python
  repo: https://github.com/pedku/PROYECTO-LAB
  plan: free
  envVars:
  - key: DATABASE_URL
    sync: false
  - key: SECRET_KEY
    sync: false
  region: oregon
  buildCommand: |
    pip install --upgrade pip
    pip install -r requirements.txt
  startCommand: python init_db.py && gunicorn -w 4 -b 0.0.0.0:$PORT qr_access_system.app:app
  autoDeployTrigger: "off"
version: "1"
