"""Add schedule type for day or date

Revision ID: 57d545afc024
Revises: 66c8c5448269
Create Date: 2025-03-28 07:39:52.996538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57d545afc024'
down_revision = '66c8c5448269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.alter_column('lab_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('access_logs_lab_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'profes', ['profe_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'laboratories', ['lab_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('profes', schema=None) as batch_op:
        batch_op.drop_constraint('profes_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_type', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('day_of_week', sa.String(length=20), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_constraint('schedules_lab_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'profes', ['profe_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'laboratories', ['lab_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('schedules_lab_id_fkey', 'laboratories', ['lab_id'], ['id'])
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('day_of_week')
        batch_op.drop_column('schedule_type')

    with op.batch_alter_table('profes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('profes_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('access_logs_lab_id_fkey', 'laboratories', ['lab_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('lab_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
