"""Agregar columna user_id a la tabla profes

Revision ID: 6cd00148195e
Revises: f5cac7bdfa7a
Create Date: 2025-03-09 16:26:57.180359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cd00148195e'
down_revision = 'f5cac7bdfa7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.alter_column('lab_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('access_logs_lab_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'laboratories', ['lab_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'profes', ['profe_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('profes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('profes_username_key', type_='unique')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('password_hash')
        batch_op.drop_column('username')

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_constraint('schedules_lab_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'laboratories', ['lab_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'profes', ['profe_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('schedules_lab_id_fkey', 'laboratories', ['lab_id'], ['id'])

    with op.batch_alter_table('profes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('profes_username_key', ['username'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('access_logs_lab_id_fkey', 'laboratories', ['lab_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('lab_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
