"""Add cascade delete to schedules

Revision ID: 8c61cad956ce
Revises: 33e1c1d38e7a
Create Date: 2025-03-05 14:36:29.853240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c61cad956ce'
down_revision = '33e1c1d38e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_constraint('schedules_lab_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'laboratories', ['lab_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('schedules_lab_id_fkey', 'laboratories', ['lab_id'], ['id'])

    # ### end Alembic commands ###
