"""Add cascade delete to access_logs

Revision ID: c33d3a7f4b0e
Revises: 8c61cad956ce
Create Date: 2025-03-05 14:46:06.909603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c33d3a7f4b0e'
down_revision = '8c61cad956ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.drop_constraint('access_logs_lab_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'laboratories', ['lab_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('access_logs_lab_id_fkey', 'laboratories', ['lab_id'], ['id'])

    # ### end Alembic commands ###
