"""Agregar columnas username y password_hash a la tabla profes

Revision ID: f5cac7bdfa7a
Revises: 7278fca119b7
Create Date: 2025-03-09 16:11:53.556244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5cac7bdfa7a'
down_revision = '7278fca119b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.alter_column('lab_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('access_logs_profe_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('access_logs_lab_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'profes', ['profe_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'laboratories', ['lab_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('profes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=200), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_constraint('schedules_lab_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('schedules_profe_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'laboratories', ['lab_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'profes', ['profe_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('schedules_profe_id_fkey', 'profes', ['profe_id'], ['id'])
        batch_op.create_foreign_key('schedules_lab_id_fkey', 'laboratories', ['lab_id'], ['id'])

    with op.batch_alter_table('profes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('access_logs_lab_id_fkey', 'laboratories', ['lab_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('access_logs_profe_id_fkey', 'profes', ['profe_id'], ['id'])
        batch_op.alter_column('lab_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
